# Optimal Rotation by QCQP

In [5]:
import cvxpy as cp
import numpy as np

In [24]:
# Problem data.
m = 10
n = 2
np.random.seed(1)
X = np.random.randn(m, n)
Y = np.random.randn(m, n)
A = X.transpose().dot(X)
b = (Y.transpose().dot(X)).flatten()
A, b, b.flatten().shape

(array([[10.37120677, -7.78585787],
        [-7.78585787, 14.17595674]]),
 array([[-3.07230232,  2.16825185],
        [-0.79225915,  2.29682612]]),
 (4,))

In [22]:
Y[:, 1].transpose().dot(X)

array([-0.79225915,  2.29682612])

In [12]:
# QCQP test.
# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A@x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

[-1.79109255e-19  2.85112420e-02  2.79973443e-19  3.37658729e-20
 -2.72802663e-19  1.49285011e-01 -9.94082533e-20  8.35373900e-20
  2.46718649e-01  5.78224144e-01 -4.03739463e-19  1.01242860e-03
 -9.28486180e-20  2.26767464e-01 -1.58813678e-19 -8.97232272e-20
 -1.22145729e-19 -1.51509428e-19  1.12060672e-19 -3.48318635e-19]
[ 2.50938945  0.          2.78354615  1.79425782 13.08579183  0.
  0.73716363  3.35344995  0.          0.          8.93825054  0.
  7.02955161  0.          4.71068649  3.18873635  2.06090107 10.08166738
  3.0481157   8.53268239]
